spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:myDb;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  jpa:
    show-sql: true

server:
  port: 8089

logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
